### PR TITLE
First stab at time use disclaimers

### PR DESCRIPTION
**Pull request by akeranen**

### CODE REVIEW

**Comment by fluffy** [comment]
This looks reasonable to me. I think you bring up a good point in the email with now being the time that the record was sent in the stream. I have seen this used where the  base time is set to 0 and it is a stream. Every 60 seconds the sensor produces a new sensor measurement with a time of 0 in that stream.

**Comment by akeranen** [comment]
@fluffy I made PR #128 to address the SensML "now" issue

**Review by fluffy — APPROVED** [review]
LGTM

**Comment by akeranen** [comment]
Made redundant by #129

**Pull request closed without merging**
