### PR TITLE
Different file extensions for different media types

### PR DESCRIPTION
**Pull request by akeranen**

### CODE REVIEW

**Comment by cabo** [comment]
Why is there no sensml+cbor?  (I can't really find where sensml+json is actually defined.)

```
doing this. SenML defines a separate mime type (TODO) to indicate Sensor
```

Is that really TODO?

**Comment by akeranen** [comment]
sensml+json is defined in "Multiple Datapoints". Perhaps could be improved. That TODO was fixed in https://github.com/core-wg/senml-spec/commit/a5095b74d8c702ae5fe60aa129dcfdd2d5322331

**Comment by cabo** [comment]
That is an example, no?  Where is the definition?

**Comment by cabo** [comment]
(In CBOR, SensML would just be a CBOR sequence.  No need even for an array around that.)
See also RFC 7464...

**Pull request merged**
