### PR TITLE
Clarification to name character restrictions for URIs (from Peter)

### PR DESCRIPTION
**Pull request by akeranen**

### CODE REVIEW

**Comment by akeranen** [comment]
This PR should be merged only after PR #83

**Review by fluffy — APPROVED** [review]

**Review by fluffy — APPROVED** [review]
LGTM

**Comment by stpeter** [comment]
That looks good. Please note that RFC 2141 has been obsoleted by RFC 8141.

**Comment by cabo** [comment]
@stpeter: Indeed, we fixed the RFC 2141 reference in -11.

If you can have a look at https://tools.ietf.org/rfcdiff?url2=draft-ietf-core-senml-11.txt and send some comments to the mailing list, that would be highly appreciated; we'd like to push this to the IESG now.

**Pull request merged**
